# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71da38302017beb0690adb1c2bfd8f4f7f35287cd018334b865479c49bcd95af6207b41925e7645b8d1cc001974b38492d7230d929b64dc09faf2bdc04f24356

test:
  secret_key_base: 88d1f155af82a192b8cae296756b5d11a858414c62b44ae1cabfe5e89c3a4f94b80caab9dafa18ead84eae66590dbdc21503f13f0f6ea2534a713462093cac6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
